<a href="https://colab.research.google.com/github/SamanthaGoldhammer/FTI_Project1/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Global AI Content Impact

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/Passwords/sampled_passwords.csv"
df = pd.read_csv(url)
df.head()

                        Password  Strength_Level
0                   abrocomeLlll               1
1       EZ&c%{(1~;eu7a/uUGL&B}%Z               4
2  ]|VWl>90|3\]dL~_y*fOQa$5Q~?2q               4
3                   accordancyy]               2
4                          xjemt               0

In [5]:
df.columns=(df.columns.str.strip())
df.columns=(df.columns.str.lower())
df.columns

Index(['password', 'strength_level'], dtype='object')

In [6]:
df.isnull().sum()

password          0
strength_level    0
dtype: int64

In [7]:
df.shape

(1500112, 2)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500112 entries, 0 to 1500111
Data columns (total 2 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   password        1500112 non-null  object
 1   strength_level  1500112 non-null  int64
dtypes: int64(1), object(1)
memory usage: 22.9+ MB

In [9]:
print(df.duplicated().sum())

38643

In [11]:
df=df.drop_duplicates()
print(df.duplicated().sum())

0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1461469 entries, 0 to 1500111
Data columns (total 2 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   password        1461469 non-null  object
 1   strength_level  1461469 non-null  int64
dtypes: int64(1), object(1)
memory usage: 33.5+ MB

In [13]:
df.head()

                        password  strength_level
0                   abrocomeLlll               1
1       EZ&c%{(1~;eu7a/uUGL&B}%Z               4
2  ]|VWl>90|3\]dL~_y*fOQa$5Q~?2q               4
3                   accordancyy]               2
4                          xjemt               0